[workspace]
resolver = "2"
exclude = ["fuzz"]
members = [
    "src/llvm-ir",
    "src/llvm-ir-parser",
    "src/llvm-analysis",
    "src/llvm-transforms",
    "src/llvm-codegen",
    "src/llvm-target-x86",
    "src/llvm-target-arm",
    "src/llvm-target-riscv",
    "src/llvm-target-wasm",
    "src/llvm-bitcode",
    "src/llvm",
    "src/llvm-bench",
    "src/llvm-rustc-backend",
    "src/llvm-jit",
    "examples/tikv_jit",
    "bench/fuzz",
]
