//! Random LLVM IR generator for differential fuzzing.
//!
//! Generates seed-deterministic, valid SSA IR programs for use in fuzz testing.
//! All generated functions are single-block with 1–3 i64 arguments returning i64,
//! containing 3–12 arithmetic instructions.

use llvm_ir::{Builder, Context, FunctionId, InstrKind, Linkage, Module, ValueRef};
use rand::rngs::SmallRng;
use rand::{Rng, SeedableRng};

/// Operation kinds that the generator may emit (all i64 → i64 binary ops).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum BinOp {
    Add,
    Sub,
    Mul,
    And,
    Or,
    Xor,
}

const ALL_BINOPS: &[BinOp] = &[
    BinOp::Add,
    BinOp::Sub,
    BinOp::Mul,
    BinOp::And,
    BinOp::Or,
    BinOp::Xor,
];

/// Seed-deterministic random IR generator.
pub struct FuzzGen {
    rng: SmallRng,
}

impl FuzzGen {
    /// Create a new generator seeded with `seed`.
    pub fn new(seed: u64) -> Self {
        Self {
            rng: SmallRng::seed_from_u64(seed),
        }
    }

    /// Generate a random single-block function with 1–3 i64 args returning i64.
    ///
    /// The function body has 3–12 arithmetic instructions (no branches).
    /// Returns the `FunctionId` of the generated function.
    pub fn gen_function(
        &mut self,
        ctx: &mut Context,
        module: &mut Module,
    ) -> FunctionId {
        let n_args: usize = self.rng.random_range(1..=3);
        let n_instrs: usize = self.rng.random_range(3..=12);

        let i64_ty = ctx.i64_ty;
        let param_tys = vec![i64_ty; n_args];
        let param_names: Vec<String> = (0..n_args).map(|i| format!("a{}", i)).collect();

        let mut b = Builder::new(ctx, module);
        let fid = b.add_function(
            "fuzz_fn",
            b.ctx.i64_ty,
            param_tys,
            param_names,
            false,
            Linkage::External,
        );

        let entry = b.add_block("entry");
        b.position_at_end(entry);

        // `defined` holds all ValueRefs we can use as operands.
        let mut defined: Vec<ValueRef> = (0..n_args as u32)
            .map(|i| b.get_arg(i))
            .collect();

        for idx in 0..n_instrs {
            // Pick two random operands from the currently defined values.
            let lhs_i = self.rng.random_range(0..defined.len());
            let rhs_i = self.rng.random_range(0..defined.len());
            let lhs = defined[lhs_i];
            let rhs = defined[rhs_i];

            let op = ALL_BINOPS[self.rng.random_range(0..ALL_BINOPS.len())];
            let name = format!("v{}", idx);

            let result = match op {
                BinOp::Add => b.build_add(name, lhs, rhs),
                BinOp::Sub => b.build_sub(name, lhs, rhs),
                BinOp::Mul => b.build_mul(name, lhs, rhs),
                BinOp::And => b.build_and(name, lhs, rhs),
                BinOp::Or  => b.build_or(name, lhs, rhs),
                BinOp::Xor => b.build_xor(name, lhs, rhs),
            };

            defined.push(result);
        }

        // Return the last defined value.
        let ret_val = *defined.last().unwrap();
        b.build_ret(ret_val);

        fid
    }

    /// Compute the expected return value of a generated function by interpreting
    /// its single entry block symbolically with concrete argument values.
    ///
    /// Arguments are assigned the values `[1, 2, 3]` (truncated to `n_args`).
    ///
    /// # Panics
    /// Panics if the function contains unsupported instructions (should not happen
    /// for functions generated by [`FuzzGen::gen_function`]).
    pub fn interpret(ctx: &Context, module: &Module, fid: FunctionId) -> i64 {
        // Concrete argument values: arg0=1, arg1=2, arg2=3.
        let arg_vals: &[i64] = &[1, 2, 3];

        let func = module.function(fid);
        assert!(!func.blocks.is_empty(), "function has no blocks");
        let entry = &func.blocks[0];

        // Map InstrId → computed i64 value.
        let mut values: std::collections::HashMap<llvm_ir::InstrId, i64> =
            std::collections::HashMap::new();

        // Helper: resolve a ValueRef to an i64.
        let resolve = |vref: ValueRef,
                       values: &std::collections::HashMap<llvm_ir::InstrId, i64>|
         -> i64 {
            match vref {
                ValueRef::Argument(aid) => arg_vals.get(aid.0 as usize).copied().unwrap_or(0),
                ValueRef::Instruction(iid) => *values.get(&iid).expect("use before def"),
                ValueRef::Constant(cid) => match ctx.get_const(cid) {
                    llvm_ir::ConstantData::Int { val, .. } => *val as i64,
                    _ => 0,
                },
                ValueRef::Global(_) => 0,
            }
        };

        // Interpret body instructions.
        for &iid in &entry.body {
            let instr = func.instr(iid);
            let result: i64 = match &instr.kind {
                InstrKind::Add { lhs, rhs, .. } => {
                    resolve(*lhs, &values).wrapping_add(resolve(*rhs, &values))
                }
                InstrKind::Sub { lhs, rhs, .. } => {
                    resolve(*lhs, &values).wrapping_sub(resolve(*rhs, &values))
                }
                InstrKind::Mul { lhs, rhs, .. } => {
                    resolve(*lhs, &values).wrapping_mul(resolve(*rhs, &values))
                }
                InstrKind::And { lhs, rhs } => {
                    resolve(*lhs, &values) & resolve(*rhs, &values)
                }
                InstrKind::Or { lhs, rhs } => {
                    resolve(*lhs, &values) | resolve(*rhs, &values)
                }
                InstrKind::Xor { lhs, rhs } => {
                    resolve(*lhs, &values) ^ resolve(*rhs, &values)
                }
                _ => panic!("unexpected instruction kind in generated function: {:?}", instr.kind),
            };
            values.insert(iid, result);
        }

        // Evaluate the terminator (must be `ret`).
        if let Some(tid) = entry.terminator {
            let term = func.instr(tid);
            match &term.kind {
                InstrKind::Ret { val: Some(vref) } => resolve(*vref, &values),
                InstrKind::Ret { val: None } => 0,
                _ => panic!("unexpected terminator: {:?}", term.kind),
            }
        } else {
            panic!("entry block has no terminator");
        }
    }
}

// ── tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use llvm_ir::{Context, Module};

    /// Generated function must have a valid entry block with a `ret` terminator.
    #[test]
    fn gen_function_terminates() {
        let mut ctx = Context::new();
        let mut module = Module::new("fuzz");
        let fid = FuzzGen::new(42).gen_function(&mut ctx, &mut module);
        let func = module.function(fid);
        assert!(!func.blocks.is_empty(), "function should have blocks");
        let entry = &func.blocks[0];
        let tid = entry.terminator.expect("entry block must have a terminator");
        match &func.instr(tid).kind {
            InstrKind::Ret { .. } => {}
            other => panic!("expected ret terminator, got {:?}", other),
        }
    }

    /// Generated function uses only defined values (no use-before-def).
    #[test]
    fn gen_function_valid_ssa() {
        let mut ctx = Context::new();
        let mut module = Module::new("fuzz");
        let fid = FuzzGen::new(99).gen_function(&mut ctx, &mut module);
        // If interpretation succeeds without panicking, all uses were defined.
        let _ = FuzzGen::interpret(&ctx, &module, fid);
    }

    /// Same seed always produces the same IR text (deterministic generation).
    #[test]
    fn gen_function_reproducible() {
        use llvm_ir::Printer;

        let mut ctx1 = Context::new();
        let mut mod1 = Module::new("fuzz");
        let fid1 = FuzzGen::new(7).gen_function(&mut ctx1, &mut mod1);
        let text1 = Printer::new(&ctx1).print_module(&mod1);

        let mut ctx2 = Context::new();
        let mut mod2 = Module::new("fuzz");
        let fid2 = FuzzGen::new(7).gen_function(&mut ctx2, &mut mod2);
        let text2 = Printer::new(&ctx2).print_module(&mod2);

        assert_eq!(text1, text2, "same seed must produce identical IR");
        // Also sanity-check both interpret to the same value.
        let v1 = FuzzGen::interpret(&ctx1, &mod1, fid1);
        let v2 = FuzzGen::interpret(&ctx2, &mod2, fid2);
        assert_eq!(v1, v2);
    }

    /// Interpretation of a minimal add function returns `arg0 + arg0 = 1 + 1 = 2`.
    ///
    /// We build the function manually here rather than depending on a specific seed
    /// so the test is robust to generator changes.
    #[test]
    fn expected_output_add() {
        // Build: define i64 @fuzz_fn(i64 %a0) { entry: %v0 = add i64 %a0, %a0; ret %v0 }
        // With arg0 = 1, expected = 1 + 1 = 2.
        let mut ctx = Context::new();
        let mut module = Module::new("fuzz");
        {
            let mut b = Builder::new(&mut ctx, &mut module);
            b.add_function(
                "fuzz_fn",
                b.ctx.i64_ty,
                vec![b.ctx.i64_ty],
                vec!["a0".to_string()],
                false,
                Linkage::External,
            );
            let entry = b.add_block("entry");
            b.position_at_end(entry);
            let a0 = b.get_arg(0);
            let sum = b.build_add("v0", a0, a0);
            b.build_ret(sum);
        }

        let fid = llvm_ir::FunctionId(0);
        let result = FuzzGen::interpret(&ctx, &module, fid);
        assert_eq!(result, 2, "add a0 + a0 with a0=1 should return 2");
    }

    /// Interpretation with a sub: a0 - a1 = 1 - 2 = -1.
    #[test]
    fn expected_output_sub() {
        let mut ctx = Context::new();
        let mut module = Module::new("fuzz");
        {
            let mut b = Builder::new(&mut ctx, &mut module);
            b.add_function(
                "fuzz_fn",
                b.ctx.i64_ty,
                vec![b.ctx.i64_ty, b.ctx.i64_ty],
                vec!["a0".to_string(), "a1".to_string()],
                false,
                Linkage::External,
            );
            let entry = b.add_block("entry");
            b.position_at_end(entry);
            let a0 = b.get_arg(0);
            let a1 = b.get_arg(1);
            let diff = b.build_sub("v0", a0, a1);
            b.build_ret(diff);
        }

        let fid = llvm_ir::FunctionId(0);
        let result = FuzzGen::interpret(&ctx, &module, fid);
        assert_eq!(result, -1, "sub a0 - a1 with a0=1, a1=2 should return -1");
    }
}
